site_name: Bitextor
site_url: null
use_directory_urls: False
site_description: Generates translation memories from multilingual websites.
site_author: Bitextor Team

repo_url: https://github.com/bitextor/bitextor/

theme:
    name: readthedocs
    nav_style: dark

nav:
    - Home: 'README.md'
    - Installation: 'INSTALL.md'
    - Configuration: 'CONFIG.md'

markdown_extensions:
    - toc:
        toc_depth: 6
