site_name: Bitextor
site_url: null
use_directory_urls: False
site_description: Generates translation memories from multilingual websites.
site_author: Bitextor Team

repo_url: https://github.com/bitextor/bitextor/

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"

theme:
    name: readthedocs
    nav_style: dark

nav:
    - Home: 'README.md'
    - Installation: 'INSTALL.md'
    - Configuration: 'CONFIG.md'
    - Output: 'OUTPUT.md'

markdown_extensions:
    - toc:
        toc_depth: 6
