name: Build and execute Bitextor tests
on:
   push:
      paths-ignore:
         - '**.md'
         - 'docs/**'
         - 'img/**'
   pull_request:
      paths-ignore:
         - '**.md'
         - 'docs/**'
         - 'img/**'
jobs:
   build_and_testing:
      name: Build and testing
      runs-on: ubuntu-20.04
      timeout-minutes: 1440
      steps:
      -  name: Install required linux packages
         run: |
            apt-get --assume-yes update
            apt-get --assume-yes install cmake automake liblzma-dev time poppler-utils libboost-all-dev pkg-config curl git pigz wget zlib1g zlib1g-dev libgoogle-perftools-dev libsparsehash-dev coreutils uchardet libuchardet-dev libzip-dev libhunspell-dev hunspell-fr
            # sponge utility (just for CI)
            apt-get --assume-yes install moreutils
      -  name: Set up Python3
         uses: actions/setup-python@v2
         with:
            python-version: '3.8.5'
            architecture: 'x64'
      -  name: Install Python dev tools
         run: |
            pip3 install --upgrade pip
            sudo apt-get --assume-yes install python3-venv python3-setuptools
            pip3 install Cython
      -  name: Set up JDK
         uses: actions/setup-java@v1
         with:
            java-version: 8
            java-package: jdk
            architecture: x64
      -  uses: actions/checkout@v2
      -  name: Checkout submodules
         run: git submodule update --init --force --recursive
      -  name: Install additional python requirements
         run: |
            pip3 install .[all]
            pip3 install ./third_party/bicleaner
            pip3 install ./third_party/bicleaner-ai
            pip3 install ./third_party/kenlm --install-option="--max_order 7"
            pip3 install ./third_party/bifixer
            pip3 install ./third_party/biroamer
            python3 -c "from flair.models import SequenceTagger; SequenceTagger.load('flair/ner-english-fast')"
            pip3 install ./third_party/neural-document-aligner
            pip3 install ./third_party/vecalign
      -  name: Setup golang
         uses: actions/setup-go@v2
         with:
            go-version: 1.17.3
      -  name: Install giashard
         run: |
            go install github.com/paracrawl/giashard/...@latest
      -  name: Compiling bitextor and submodules
         run: |
            mkdir build_cmake && cd build_cmake
            cmake -DSKIP_MGIZA=ON -DCMAKE_INSTALL_PREFIX=/usr ..
            make -j
            sudo make install
      -  name: Run tests
         id: tests
         env:
            WORK: ${{ github.workspace }}
         run: |
            chmod 775 ./tests/run-tests-min.sh
            ./tests/run-tests-min.sh -w "$WORK" -j 4
      -  name: Print log of tests which failed
         # https://github.com/actions/runner/issues/1173
         #if: ${{ steps.tests.conclusion != 'success' }}
         if: ${{ always() }}
         env:
            WORK: ${{ github.workspace }}
         run: |
            if [[ -f "${WORK}/data/fails.log" ]]; then
               while read line; do
                  eval "array=($line)"
                  status=${array[0]}
                  notest=${array[1]}
                  exit_code=${array[2]}

                  str="# Test $notest (exit code / desc.: $exit_code) #"
                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
                  echo "$str"
                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"

                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
                  else
                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
                  fi

                  echo ""
               done < "${WORK}/data/fails.log"
            else
               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
               exit 1
            fi
      -  name: Print log subsample of tests which succeeded
         # https://github.com/actions/runner/issues/1173
         #if: ${{ steps.tests.conclusion == 'success' }}
         if: ${{ always() }}
         env:
            WORK: ${{ github.workspace }}
         run: |
            for report_file in $(ls ${WORK}/reports/*); do
               notest=$(basename "$report_file" | sed -E 's/([0-9]+).*/\1/')
               sent_file=$(cat "$report_file" | grep "output:.*.sent.gz" | sed -E 's/.*output:\ (\/.*[.]sent[.]gz).*$/\1/' | sort -u)

               if [[ -f "$sent_file" ]]; then
                  md5=$(zcat "$sent_file" | md5sum | awk '{print $1}')
                  nolines=$(zcat "$sent_file" | wc -l)

                  str="# Test $notest (md5: $md5) #"
                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
                  echo "$str"
                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"

                  if [[ "$nolines" -gt "15" ]]; then
                     awk -v prefix="(sent.gz test $notest)" '{print prefix" "$0}' \
                        <(zcat "$sent_file" | sponge | head -6) <(zcat "$sent_file" | tail -5)
                  else
                     awk -v prefix="(sent.gz test $notest)" '{print prefix" "$0}' <(zcat "$sent_file")
                  fi
               else
                  echo "(warning) No sent file found for test $notest (sent.gz file: $sent_file)"
               fi

               echo ""
            done
